---
- import_tasks: 'bond_configuration.yml'
  when: interfaces_bond_interfaces is defined

- import_tasks: 'bridge_configuration.yml'
  when: interfaces_bridge_interfaces is defined

- import_tasks: 'ethernet_configuration.yml'
  when: interfaces_ether_interfaces is defined
